### ISSUE TITLE
To make Circleci Dashboard more compact?

### ISSUE THREAD

**Issue by rgleason** [jongough/testplugin_pi#204]
Is it possible to have in the circleci/config.yml all the builds put under a "build_all"  without changing to much about our build flexability ?   
The reason I say this is the Dashboard that is used with "build_all" seems to be much more compact and convenient
See this yml   https://github.com/Rasbats/shipdriver_pi/blob/master/.circleci/config.yml    line 161
The difference is shown here

![Screenshot (6)](https://user-images.githubusercontent.com/2363959/139492184-6167e2e2-16ae-40ee-9814-fecd9bb3475a.png)
![Screenshot (5)](https://user-images.githubusercontent.com/2363959/139492173-5fec1470-c6b6-47d6-b87b-0398cdaf6c1f.png)

```
workflows:
  version: 2
  build_all:
    jobs:

      - build-flatpak-arm64:
          <<: *std-filters

      - build-flatpak-x86-1808:
          <<: *std-filters

      - build-flatpak-x86-2008:
          <<: *std-filters
```
