### ISSUE TITLE
MacOS Builds - Circleci resource deprecation  

### ISSUE THREAD

**Issue by rgleason** [jongough/testplugin_pi#298]
https://discuss.circleci.com/t/macos-resource-deprecation-update/46891

```
Phase 1 - mid-March 2023
    a. Xcode 14.2.0 is the last Xcode version that will be supported by medium and large.
    b. We will automatically upgrade jobs for customers on our Free plan to our Gen2 resources (macos.x86.medium.gen2).

Phase 2 - October 2, 2023
    a. The macOS medium and large resource classes are no longer available.
    b. Any jobs specifying medium and large will fail with an Invalid resource class error.
    c. If your project config doesn’t specify a macOS resource class, jobs will be defaulted to macos.x86.medium.gen2.

If you are using the medium resource, we recommend updating to our Gen2 resource.

    Update the resource class key in your configuration file from medium to macos.x86.medium.gen2.
    Building with Gen2 will reduce your time to market by up to 50%

```

Use  macos.x86.medium.gen2   ?

**Comment by rgleason** [comment]
https://discuss.circleci.com/t/macos-resource-deprecation-update/46891

If you are using the medium resource, we recommend updating to our Gen2 resource.

    Update the resource class key in your configuration file from medium to macos.x86.medium.gen2.
    Building with Gen2 will reduce your time to market by up to 50%

**Comment by rgleason** [comment]
How should we change circleci/config.yml?

Add

  resource class: macos.x86.medium.gen2

Somewhere?   https://circleci.com/docs/using-macos/

```
    build-macos:
        macos:
            xcode: "12.5.1"
        environment:
        - OCPN_TARGET:  macos
        - CLOUDSMITH_PKG_EXT: pkg
        - DEPLOY_USE_ORB: true
        - WX_VER: 312
        steps:
        - checkout
        - run: chmod a+x ci/*.sh
        - run: bash ci/circleci-build-macos.sh
        - deploy-code
    build-macos-wx32:
        macos:
            xcode: "12.5.1"
        environment:
        - OCPN_TARGET:  macos
        - CLOUDSMITH_PKG_EXT: pkg
        - DEPLOY_USE_ORB: true
        - WX_VER: 32
        steps:
        - checkout
        - run: chmod a+x ci/*.sh
        - run: bash ci/circleci-build-macos.sh
        - deploy-code
```

**Comment by rgleason** [comment]
Testplugin v1.0.237   uses the following:

```
   build-macos:
        macos:
            xcode: "12.5.1"
        environment:
        - OCPN_TARGET:  macos
        - CLOUDSMITH_PKG_EXT: pkg
        - DEPLOY_USE_ORB: true
        - WX_VER: 312
        steps:
        - checkout
        - run: chmod a+x ci/*.sh
        - run: bash ci/circleci-build-macos.sh
        - deploy-code
```

```
    build-msvc-2022:
        executor: win/server-2022
        environment:
        - OCPN_TARGET: MSVC
        - MSVC_VERSION: 2022
        - WX_VER: 32
        - DEPLOY_USE_ORB: true
        steps:
        - checkout
        - run: ci/circleci-build-msvc
        - deploy-code:
            install-python: true
```

**Comment by rgleason** [comment]
Currently TP1.0.238  .circleci/config.yml has

```
    build-macos-wx32:
        macos:
            xcode: "12.5.1"
        environment:
        - OCPN_TARGET:  macos
        - CLOUDSMITH_PKG_EXT: pkg
        - DEPLOY_USE_ORB: true
        - WX_VER: 32
        steps:
        - checkout
        - run: chmod a+x ci/*.sh
        - run: bash ci/circleci-build-macos.sh
        - deploy-code
```
An example using resource_class is in flatpak builds below.
We would use the more current recommended 
`  resource_class:macos.x86.medium.gen2`
but what else would change for macos? 

```
    build-flatpak-arm64-2208:
        machine:
            image: ubuntu-2004:202101-01
        resource_class: arm.medium
        environment:
        - OCPN_TARGET:  flatpak-arm64
        - FLATPAK_BRANCH: stable
        - CLOUDSMITH_PKG_EXT: gz
        - SDK_VER: 22.08
        - DEPLOY_USE_ORB: true
        steps:
        - checkout
        - run: chmod a+x ci/*.sh
        - run:
            command: bash ci/circleci-build-flatpak.sh
        - deploy-code
```
