### ISSUE TITLE
Adding Template Table for 5.10.2 - Correct?

### ISSUE THREAD

**Issue by rgleason** [jongough/testplugin_pi#401]
Jon,
Can you please take a careful look at the 5.10.2 Table at the top
https://github.com/jongough/testplugin_pi/issues/284
Is it correct now and reflect what we are building now?

Also I wonder about some of the config.yml code that we have now.

These are frozen and not being built (commented out)   Start at Line 65
https://github.com/jongough/testplugin_pi/blob/master/.circleci/config.yml#L64

 ```
 ## -------------------------------------------
 ## OpenCPN 5.6.2 Plugins  Frozen - 28/05/2023
 ## ------------------------------------------
 ## Circleci will not build for macos 11 so removed - 18/10/2023
         - build-macos:
              <<: *std-filters
         - build-msvc-2022:
             <<: *std-filters
 
 ## -------------------------------------
 ## UBUNTU OS  Frozen - 28/05/2023  DROP
 ## -------------------------------------
 ## KEEP needed for Raspbian OpenCPN v5.6
 #        - build-ubuntu-armhf-1804-buster:
 #            <<: *std-filters
```
 
 

Starting at Line 410 we have, should these be commented out just as above because they are not being built?

```
 ## ---------------------
 ## OpenCPN 5.6.2 Plugins
 ## ---------------------
     build-macos:
         macos:
             xcode: "13.4"
         environment:
         - OCPN_TARGET:  macos
         - CLOUDSMITH_PKG_EXT: pkg
         - WX_VER: 315
         - DEPLOY_USE_ORB: false
         steps:
         - checkout
         - run: chmod a+x ci/*.sh
         - run: bash ci/circleci-build-macos.sh
         - deploy-code:
             deploy_use_orb: false
 
 ## Appveyor doesn't build for Windows now.
 ## If below is used, WinXT will not work.
     build-msvc-2022:
         executor:
             name: win/server-2022
             shell: cmd.exe
         environment:
         - OCPN_TARGET: MSVC
         - MSVC_VERSION: 2022
         - WX_VER: 31
         - DEPLOY_USE_ORB: false
         steps:
         - checkout
         - run:
             privileged: False
             shell: cmd.exe
             command: ci\circleci-build-msvc.bat
         - deploy-code:
             deploy_use_orb: false
```
 

On Line 388  - We are still building this - Correct?

```
## KEEP needed for OpenCPN v5.8 Jammy wx32 build
    build-ubuntu-x86_64-2204-jammy:
```

Are there any other changes needed?
